language: ruby
sudo: false
cache: bundler

rvm:
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - jruby-1.6
  - jruby-1.7
  - jruby-9

before_install:
  gem install bundler -v 1.16.1

script:
  - bundle exec rubocop
  - bundle exec rake
